name: Build and Push Docker Image with Version

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'  # For example: v1.0.0, v2.1.3 etc

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get Version Tag or Default to 'latest'
        id: get_tag
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            echo "TAG=$TAG_NAME" >> $GITHUB_ENV
          else
            echo "TAG=latest" >> $GITHUB_ENV
          fi

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            dhrupalpatidar1313/n8n-compose-n8n:${{ env.TAG }}
            dhrupalpatidar1313/n8n-compose-n8n:latest
