name: Build and Push N8N Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push N8N Image
        uses: docker/build-push-action@v5
        with:
          context: ./n8n-custom
          file: ./n8n-custom/Dockerfile
          push: true
          tags: dhrupalpatidar1313/n8n-traefik-ngrok:latest
